name: CI

on:
  push:
    branches:
      - "*"
  pull_request:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - "^1.16"
          - "1.15"
          - "1.14"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Get Dependencies
        run: go mod download
      - name: Run Tests
        run: go test -v -race -timeout=30s ./...
