name: CI

on:
  push:
    branches:
      - "*"
  pull_request:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: "^1.17"
      - name: Get Dependencies
        run: go mod download
      - name: Run Tests
        run: go test -v -race -timeout=30s ./...
